checks = [
    "all",
    "-ST1000",  
    "-ST1003",  
    "-ST1016",  
    "-SA9003",  
    "-SA1019", 
    "-U1000",   
]


initialisms = [
    "inherit",
    "ID",
    "URL",
    "API",
    "HTTP",
    "HTTPS",
    "JSON",
    "SQL",
    "TCP",
    "TLS",
    "UUID",
]

dot_import_whitelist = [
    "github.com/onsi/gomega",
]


http_status_code_whitelist = [
    "200",
    "201",
    "204",
    "400",
    "401",
    "403",
    "404",
    "409",
    "422",
    "500",
    "502",
    "503",
]