// Package resetgen реализует генератор кода: он сканирует Go-пакеты
// в поисках структур, помеченных комментарием `// generate:reset`,
// и создаёт для каждой из них метод Reset() в файле reset.gen.go
// внутри того же пакета.
package resetgen

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
)

const (
	// ResetComment — комментарий-маркер, помечающий структуру для генерации.
	ResetComment = "generate:reset"
	// GeneratedFile — имя файла, который создаёт генератор.
	GeneratedFile = "reset.gen.go"
)

// Run обходит дерево каталогов, начиная с root, и (пере)создаёт
// reset.gen.go для каждого Go-пакета, в котором есть хотя бы одна
// структура, помеченная маркером.
func Run(root string) error {
	abs, err := filepath.Abs(root)
	if err != nil {
		return err
	}
	return filepath.Walk(abs, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if !info.IsDir() {
			return nil
		}
		name := info.Name()
		// Пропускаем служебные и скрытые каталоги.
		if name == "vendor" || name == "testdata" {
			return filepath.SkipDir
		}
		if name != "." && name != ".." && strings.HasPrefix(name, ".") {
			return filepath.SkipDir
		}
		return processDir(path)
	})
}

// processDir парсит все .go-файлы одного каталога и, если найдены
// структуры с маркером, перезаписывает reset.gen.go.
func processDir(dir string) error {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return err
	}

	fset := token.NewFileSet()
	// Группируем распарсенные файлы по имени пакета.
	filesByPkg := make(map[string][]*ast.File)

	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}
		name := entry.Name()
		// Пропускаем всё, кроме обычных .go-файлов: тесты и наш результат.
		if !strings.HasSuffix(name, ".go") ||
			strings.HasSuffix(name, "_test.go") ||
			name == GeneratedFile {
			continue
		}

		fullPath := filepath.Join(dir, name)
		f, parseErr := parser.ParseFile(fset, fullPath, nil, parser.ParseComments)
		if parseErr != nil {
			// Файл с синтаксическими ошибками пропускаем — не валим
			// генерацию для всего каталога.
			continue
		}
		filesByPkg[f.Name.Name] = append(filesByPkg[f.Name.Name], f)
	}

	for pkgName, files := range filesByPkg {
		structs := findStructs(files)
		if len(structs) == 0 {
			continue
		}
		code, genErr := generate(pkgName, structs)
		if genErr != nil {
			return fmt.Errorf("%s: %w", dir, genErr)
		}
		out := filepath.Join(dir, GeneratedFile)
		if writeErr := os.WriteFile(out, code, 0o644); writeErr != nil {
			return writeErr
		}
	}
	return nil
}

// structInfo хранит метаданные, необходимые для генерации метода Reset.
type structInfo struct {
	name   string
	fields []fieldInfo
}

// fieldInfo описывает одно поле структуры: имя и его AST-тип.
type fieldInfo struct {
	name string
	expr ast.Expr
}

// findStructs возвращает все структуры, объявление типа которых
// помечено маркером `// generate:reset`.
func findStructs(files []*ast.File) []*structInfo {
	var result []*structInfo
	for _, file := range files {
		for _, decl := range file.Decls {
			genDecl, ok := decl.(*ast.GenDecl)
			if !ok || genDecl.Tok != token.TYPE {
				continue
			}
			for _, spec := range genDecl.Specs {
				typeSpec, ok := spec.(*ast.TypeSpec)
				if !ok {
					continue
				}
				structType, ok := typeSpec.Type.(*ast.StructType)
				if !ok {
					continue
				}
				// Маркер может стоять как над всем блоком type (...), так и
				// непосредственно над конкретной структурой.
				if !hasResetComment(genDecl.Doc) && !hasResetComment(typeSpec.Doc) {
					continue
				}
				info := &structInfo{name: typeSpec.Name.Name}
				for _, field := range structType.Fields.List {
					// Встроенные (embedded) поля пропускаем.
					if len(field.Names) == 0 {
						continue
					}
					for _, n := range field.Names {
						info.fields = append(info.fields, fieldInfo{
							name: n.Name,
							expr: field.Type,
						})
					}
				}
				result = append(result, info)
			}
		}
	}
	return result
}

// hasResetComment проверяет, содержит ли группа комментариев
// маркер `generate:reset` (в форме // или /* */).
func hasResetComment(doc *ast.CommentGroup) bool {
	if doc == nil {
		return false
	}
	for _, c := range doc.List {
		text := strings.TrimSpace(c.Text)
		text = strings.TrimSpace(strings.TrimPrefix(text, "//"))
		text = strings.TrimSpace(strings.TrimPrefix(text, "/*"))
		text = strings.TrimSpace(strings.TrimSuffix(text, "*/"))
		if text == ResetComment {
			return true
		}
	}
	return false
}

// generate формирует исходник Go-файла с методами Reset для всех структур.
func generate(pkgName string, structs []*structInfo) ([]byte, error) {
	var buf bytes.Buffer
	buf.WriteString("// Code generated by cmd/reset. DO NOT EDIT.\n\n")
	fmt.Fprintf(&buf, "package %s\n\n", pkgName)

	for _, s := range structs {
		fmt.Fprintf(&buf, "func (rs *%s) Reset() {\n", s.name)
		buf.WriteString("\tif rs == nil {\n\t\treturn\n\t}\n")
		for _, f := range s.fields {
			code := genReset("rs."+f.name, f.expr)
			if code == "" {
				continue
			}
			buf.WriteString(indent(code, 1))
			buf.WriteString("\n")
		}
		buf.WriteString("}\n\n")
	}

	src := buf.Bytes()
	formatted, err := format.Source(src)
	if err != nil {
		return src, fmt.Errorf("format: %w", err)
	}
	return formatted, nil
}

// genReset возвращает код, сбрасывающий адресуемое значение target,
// статический тип которого описывается узлом expr.
func genReset(target string, expr ast.Expr) string {
	switch t := expr.(type) {
	case *ast.Ident:
		return genResetIdent(target, t)

	case *ast.StarExpr:
		return genResetPointer(target, t)

	case *ast.ArrayType:
		if t.Len == nil {
			// Слайс: обрезаем по длине, но не зануляем.
			return fmt.Sprintf("%s = %s[:0]", target, target)
		}
		// Массив фиксированной длины: сбрасываем поэлементно.
		inner := genReset(target+"[i]", t.Elt)
		if inner == "" {
			return ""
		}
		return fmt.Sprintf("for i := range %s {\n%s\n}", target, indent(inner, 1))

	case *ast.MapType:
		return fmt.Sprintf("clear(%s)", target)

	case *ast.SelectorExpr:
		// Тип из другого пакета — пробуем вызвать Reset через интерфейс.
		return fmt.Sprintf(
			"if resetter, ok := any(&%s).(interface{ Reset() }); ok {\n\tresetter.Reset()\n}",
			target,
		)

	case *ast.InterfaceType, *ast.ChanType, *ast.FuncType:
		return target + " = nil"
	}
	return ""
}

// genResetIdent генерирует сброс для идентификатора (имени типа).
func genResetIdent(target string, ident *ast.Ident) string {
	switch ident.Name {
	case "int", "int8", "int16", "int32", "int64",
		"uint", "uint8", "uint16", "uint32", "uint64", "uintptr",
		"float32", "float64", "complex64", "complex128",
		"byte", "rune":
		return target + " = 0"
	case "string":
		return target + ` = ""`
	case "bool":
		return target + " = false"
	case "error", "any":
		return target + " = nil"
	}
	// Именованный тип — пытаемся вызвать его метод Reset (no-op, если метода нет).
	return fmt.Sprintf(
		"if resetter, ok := any(&%s).(interface{ Reset() }); ok {\n\tresetter.Reset()\n}",
		target,
	)
}

// genResetPointer генерирует сброс для указателя.
func genResetPointer(target string, star *ast.StarExpr) string {
	switch inner := star.X.(type) {
	case *ast.Ident:
		// Указатель на примитив или на именованный тип.
		if isPrimitiveType(inner.Name) || inner.Name == "error" || inner.Name == "any" {
			code := genResetIdent("(*"+target+")", inner)
			return fmt.Sprintf("if %s != nil {\n%s\n}", target, indent(code, 1))
		}
		// Указатель на именованный тип — пробуем вызвать Reset.
		return fmt.Sprintf(
			"if resetter, ok := any(%s).(interface{ Reset() }); ok && %s != nil {\n\tresetter.Reset()\n}",
			target, target,
		)

	case *ast.SelectorExpr:
		return fmt.Sprintf(
			"if resetter, ok := any(%s).(interface{ Reset() }); ok && %s != nil {\n\tresetter.Reset()\n}",
			target, target,
		)

	default:
		// Указатель на слайс, мапу, анонимную структуру и т.п.
		code := genReset("(*"+target+")", star.X)
		if code == "" {
			return ""
		}
		return fmt.Sprintf("if %s != nil {\n%s\n}", target, indent(code, 1))
	}
}

// isPrimitiveType сообщает, является ли имя примитивным (встроенным) типом.
func isPrimitiveType(name string) bool {
	switch name {
	case "int", "int8", "int16", "int32", "int64",
		"uint", "uint8", "uint16", "uint32", "uint64", "uintptr",
		"float32", "float64", "complex64", "complex128",
		"byte", "rune", "string", "bool":
		return true
	}
	return false
}

// indent добавляет к каждой непустой строке s префикс из level табов.
func indent(s string, level int) string {
	prefix := strings.Repeat("\t", level)
	lines := strings.Split(s, "\n")
	for i, l := range lines {
		if l == "" {
			continue
		}
		lines[i] = prefix + l
	}
	return strings.Join(lines, "\n")
}
